<?php

/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */
add_action('wp_footer', 'lmseo_deregister_scripts');
function lmseo_deregister_scripts() {
	wp_deregister_script('wp-embed');
}

add_action('wp_enqueue_scripts', 'lmseo_index_print_styles');
function lmseo_index_print_styles() {
	global $portArchDev;

	//  Disabling CSS styles of WooCommerce blocks
	//  https://themesharbor.com/disabling-css-styles-of-woocommerce-blocks/
	wp_dequeue_style('wc-blocks-style'); //wc-blocks-integration-css
	wp_dequeue_style('wc-blocks-integration'); //wc-blocks-integration-css
	wp_dequeue_style('woocommerce-smallscreen'); //wc-blocks-integration-css
	wp_dequeue_style('woocommerce-layout'); //wc-blocks-integration-css
	wp_dequeue_style('woocommerce-general'); //wc-blocks-integration-css
	wp_dequeue_style('woocommerce-inline'); //wc-blocks-integration-css
	wp_dequeue_style('classic-theme-styles'); //wc-blocks-integration-css
	//  Dequeue Gutenberg Block Library CSS Code Snippet
	//  https://smartwp.com/remove-gutenberg-css/
	wp_dequeue_style('wp-block-library'); // wp-block-library-css
	//  https://wordpress.org/support/topic/how-to-disable-inline-styling-style-idglobal-styles-inline-css/
	wp_dequeue_style('global-styles'); //  global-styles-inline-css
	wp_dequeue_style('lmseo'); // main css
	if (!is_super_admin() || !is_admin_bar_showing() || is_wp_login()) {
		wp_deregister_script('jquery');
		wp_dequeue_script('jquery');
		wp_dequeue_script('jquery-migrate');
	}
}
/** Add Teams JS to website */
add_action('wp_enqueue_scripts', 'error404JS');
function error404JS() {
	wp_register_script('internal-errors404', get_stylesheet_directory_uri('bootstrap') . '/dist/errors/404/js/app.js', array(), '1.0', true);
	wp_enqueue_script('internal-errors404');
}
/** Add error404 JS to website */
add_action('wp_enqueue_scripts', 'error404CSS');
function error404CSS() {
	wp_register_style('errors404-css', get_stylesheet_directory_uri() . '/dist/errors/404/style.css', array(), '1.0', 'all');
	wp_enqueue_style('errors404-css');
}
/*
*remove wrappers for header and inner
*/
add_filter('genesis_markup_content-sidebar-wrap', '__return_null');
remove_action('genesis_before_content', 'custom_breadcrumbs_services_definition', 10);

add_filter('genesis_attr_content', 'contentClassesFunction');
function contentClassesFunction($attributes) {
	$attributes['class'] = $attributes['class'] . ' ' . 'container py-5 mb  -5';
	return $attributes;
}
//* Remove default loop
remove_action('genesis_loop', 'genesis_do_loop');

add_action('genesis_loop', 'genesis_404');
/**
 * This function outputs a 404 "Not Found" error message
 *
 * @since 1.6
 */
function genesis_404() {

	echo genesis_html5() ? '<article class="entry ">' : '<div class="post hentry">';

	printf('<h1 class="entry-title">%s</h1>', __('Not found, error 404', 'genesis'));
	echo '<div class="entry-content">';

	if (genesis_html5()) :

		echo '<p>' . sprintf(__('The page you are looking for no longer exists. Perhaps you can return back to the site\'s <a href="%s">homepage</a> and see if you can find what you are looking for. Or, you can try finding it by using the search form below.', 'genesis'), home_url()) . '</p>';

		echo '<p>' . get_search_form() . '</p>';

	else :
?>

		<p><?php printf(__('The page you are looking for no longer exists. Perhaps you can return back to the site\'s <a href="%s">homepage</a> and see if you can find what you are looking for. Or, you can try finding it with the information below.', 'genesis'), home_url()); ?></p>

		<h4><?php _e('Pages:', 'genesis'); ?></h4>
		<ul>
			<?php wp_list_pages('title_li='); ?>
		</ul>

		<h4><?php _e('Categories:', 'genesis'); ?></h4>
		<ul>
			<?php wp_list_categories('sort_column=name&title_li='); ?>
		</ul>

		<h4><?php _e('Authors:', 'genesis'); ?></h4>
		<ul>
			<?php wp_list_authors('exclude_admin=0&optioncount=1'); ?>
		</ul>

		<h4><?php _e('Monthly:', 'genesis'); ?></h4>
		<ul>
			<?php wp_get_archives('type=monthly'); ?>
		</ul>

		<h4><?php _e('Recent Posts:', 'genesis'); ?></h4>
		<ul>
			<?php wp_get_archives('type=postbypost&limit=100'); ?>
		</ul>

<?php
	endif;

	echo '</div>';

	echo genesis_html5() ? '</article>' : '</div>';
}

genesis();
